const SQUARE_SIZE = 10;
const GRID_COLUMNS = 16;
const GRID_ROWS = 12;

export const dimensions = {
  SQUARE_SIZE,
  GRID_COLUMNS,
  GRID_ROWS,
  GRID_WIDTH: SQUARE_SIZE * GRID_COLUMNS,
  GRID_HEIGHT: SQUARE_SIZE * GRID_ROWS,
  SQUARE_STROKE_WIDTH: 0.1,
  SQUARE_STROKE_WIDTH_MATCHED: 0.5,
  GRID_STROKE_WIDTH: 0.1,
  SCAN_LINE_WIDTH: SQUARE_SIZE * 2,
};

export const colors = {
  SQUARE_STROKE: '#212121',
  SQUARE_STROKE_MATCHED: '#FFFFFF',
  SQUARE_DARK: '#FF9800',
  SQUARE_LIGHT: '#FAFAFA',
  SQUARE_DARK_MATCHED: '#FFB74D',
  SQUARE_LIGHT_MATCHED: '#E0E0E0',
  SQUARE_SCANNED: '#757575',
  GRID_STROKE: '#616161',
};

export const speeds = {
  SCAN_LINE_SLOW: 2 * SQUARE_SIZE,
  SCAN_LINE_MEDIUM: 4 * SQUARE_SIZE,
  SCAN_LINE_FAST: 10 * SQUARE_SIZE,
  DROP_SLOW: 0.5 * SQUARE_SIZE,
  DROP_FAST: 25 * SQUARE_SIZE,
  DROP_DETACHED: 10 * SQUARE_SIZE,
};

export const keys = {
  KEY_Z: 90,
  KEY_X: 88,
  KEY_UP: 38,
  KEY_DOWN: 40,
  KEY_LEFT: 37,
  KEY_RIGHT: 39,
  KEY_ESC: 27,
  KEY_SPACE: 32,
};
