const SQUARE_SIZE = 10;
const GRID_COLUMNS = 16;
const GRID_ROWS = 12;

export const gameStates = {
  PLAYING: 'PLAYING',
  PAUSED: 'PAUSED',
  FINISHED: 'FINISHED',
  GAMEOVER: 'GAMEOVER',
};

export const dimensions = {
  SQUARE_SIZE,
  GRID_COLUMNS,
  GRID_ROWS,
  GRID_WIDTH: SQUARE_SIZE * GRID_COLUMNS,
  GRID_HEIGHT: SQUARE_SIZE * GRID_ROWS,
  SQUARE_STROKE_WIDTH: 0.1,
  SQUARE_STROKE_WIDTH_MATCHED: 0.5,
  GRID_STROKE_WIDTH: 0.1,
  SCAN_LINE_WIDTH: SQUARE_SIZE * 2,
  SCAN_LINE_STROKE_WIDTH: 0.3,
};

export const colors = {
  BACKGROUND: '#424242',
  SQUARE_STROKE: '#212121',
  SQUARE_STROKE_MATCHED: '#FFFFFF',
  SQUARE_DARK: '#FF9800',
  SQUARE_LIGHT: '#FAFAFA',
  SQUARE_DARK_MATCHED: '#FFB74D',
  SQUARE_LIGHT_MATCHED: '#E0E0E0',
  SQUARE_SCANNED: '#757575',
  GRID_STROKE: '#616161',
  SCAN_LINE: '#FFFFFF',
  SCANNED: '#212121',
  LABEL: '#000000',
  INFO: '#FAFAFA',
};

export const speeds = {
  SCAN_LINE_SLOW: 2 * SQUARE_SIZE,
  SCAN_LINE_MEDIUM: 4 * SQUARE_SIZE,
  SCAN_LINE_FAST: 10 * SQUARE_SIZE,
  DROP_SLOW: 0.5 * SQUARE_SIZE,
  DROP_FAST: 25 * SQUARE_SIZE,
  DROP_DETACHED: 15 * SQUARE_SIZE,
};

export const keys = {
  R: 82,
  Z: 90,
  X: 88,
  UP: 38,
  DOWN: 40,
  LEFT: 37,
  RIGHT: 39,
  ESC: 27,
  SPACE: 32,
};
